name: Test

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          client/cargo/registry
          client/.cargo/git
          client/target
          server/cargo/registry
          server/.cargo/git
          server/target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('rust-toolchain.toml') }}
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2021-12-16-x86_64
        target: thumbv7em-none-eabihf
        override: true
        components: rustfmt, clippy

    - name: Lint client app
      env:
        RUSTFLAGS: -Dwarnings
      working-directory: ./client/app
      run: cargo clippy

    - name: Format client app
      working-directory: ./client/app
      run: cargo fmt -- --check

    - name: Test client app
      working-directory: ./client/app
      run: cargo test


    - name: Lint client embedded-app
      env:
        RUSTFLAGS: -Dwarnings
      working-directory: ./client/embedded-app
      run: cargo clippy --target thumbv7em-none-eabihf

    - name: Format client app
      working-directory: ./client/embedded-app
      run: cargo fmt -- --check

    - name: Test client app
      working-directory: ./client/embedded-app
      run: cargo test

      
    - name: Lint network-protocol
      env:
        RUSTFLAGS: -Dwarnings
      working-directory: ./network-protocol
      run: cargo clippy

    - name: Format network-protocol
      working-directory: ./network-protocol
      run: cargo fmt -- --check

    - name: Test network-protocol
      working-directory: ./network-protocol
      run: cargo test


    - name: Lint server app
      env:
        RUSTFLAGS: -Dwarnings
      working-directory: ./server/app
      run: cargo clippy

    - name: Format server app
      working-directory: ./server/app
      run: cargo fmt -- --check

    - name: Test server app
      working-directory: ./server/app
      run: cargo test


    - name: Lint server embedded-app
      env:
        RUSTFLAGS: -Dwarnings
      working-directory: ./server/embedded-app
      run: cargo clippy --target thumbv7em-none-eabihf

    - name: Format server embedded-app
      working-directory: ./server/embedded-app
      run: cargo fmt -- --check

    - name: Test server embedded-app
      working-directory: ./server/embedded-app
      run: cargo test
